const products = [
  {
    id: 1,
    name: "Red Dress",
    price: 59.99,
    image: "../images/red-dress1.jpg",
    images: ["../images/red-dress1.jpg", "../images/red-dress2.jpg"],
    colors: ["Red", "Black", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    description: "Elegant red evening dress, perfect for parties and special occasions.",
    category: "women-dresses"
  },
  {
    id: 2,
    name: "Men's Leather Watch",
    price: 120.00,
    image: "../images/watch1.jpg",
    images: ["../images/watch1.jpg", "../images/watch2.jpg"],
    colors: ["Black", "Brown"],
    sizes: ["One Size"],
    description: "Classic men's leather strap watch with a durable stainless steel case.",
    category: "men-watches"
  },
  {
    id: 3,
    name: "Ladies Handbag",
    price: 75.50,
    image: "../images/handbag1.jpg",
    images: ["../images/handbag1.jpg", "../images/handbag2.jpg"],
    colors: ["Black", "Beige", "Brown"],
    sizes: ["One Size"],
    description: "Stylish handbag made with premium leather. Spacious and elegant.",
    category: "women-bags"
  },
  {
    id: 4,
    name: "Men's Casual Shoes",
    price: 89.99,
    image: "../images/mens-shoes1.jpg",
    images: ["../images/mens-shoes1.jpg", "../images/mens-shoes2.jpg"],
    colors: ["Brown", "Black", "Grey"],
    sizes: ["40", "41", "42", "43", "44"],
    description: "Comfortable and stylish men's casual shoes, perfect for everyday wear.",
    category: "men-shoes"
  },
  {
    id: 5,
    name: "Blue Evening Gown",
    price: 130.00,
    image: "../images/blue-gown.jpg",
    images: ["../images/blue-gown.jpg", "../images/blue-gown2.jpg"],
    colors: ["Blue", "Navy", "Silver"],
    sizes: ["S", "M", "L"],
    description: "Glamorous blue evening gown designed for elegance and comfort.",
    category: "women-dresses"
  },
  {
    id: 6,
    name: "Gold Necklace",
    price: 220.00,
    image: "../images/gold-necklace.jpg",
    images: ["../images/gold-necklace.jpg", "../images/gold-necklace2.jpg"],
    colors: ["Gold"],
    sizes: ["One Size"],
    description: "Beautiful gold necklace with intricate detailing. Perfect gift idea.",
    category: "women-jewellery"
  },
  {
    id: 7,
    name: "White Sneakers",
    price: 65.00,
    image: "../images/white-sneakers.jpg",
    images: ["../images/white-sneakers.jpg", "../images/white-sneakers2.jpg"],
    colors: ["White", "Black"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    description: "Trendy and lightweight white sneakers suitable for casual outfits.",
    category: "women-shoes"
  },
  {
    id: 8,
    name: "Men's Belt",
    price: 35.00,
    image: "../images/mens-belt.jpg",
    images: ["../images/mens-belt.jpg"],
    colors: ["Black", "Brown"],
    sizes: ["M", "L", "XL"],
    description: "Durable men's leather belt available in multiple colors.",
    category: "men-belts"
  },
  {
    id: 9,
    name: "Ladies Shoes",
    price: 80.00,
    image: "../images/ladies-shoes.jpg",
    images: ["../images/ladies-shoes.jpg", "../images/ladies-shoes2.jpg"],
    colors: ["Red", "Black", "Nude"],
    sizes: ["36", "37", "38", "39", "40"],
    description: "Chic and comfortable ladies' heels for formal and casual wear.",
    category: "women-shoes"
  },
  {
    id: 10,
    name: "Men's Formal Shirt",
    price: 55.00,
    image: "../images/formal-shirt.jpg",
    images: ["../images/formal-shirt.jpg", "../images/formal-shirt2.jpg"],
    colors: ["White", "Blue", "Grey"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "Smart men's formal shirt made from premium cotton fabric.",
    category: "men-clothes"
  },
  {
    id: 11,
    name: "Women's Handbag",
    price: 95.00,
    image: "../images/women-handbag.jpg",
    images: ["../images/women-handbag.jpg", "../images/women-handbag2.jpg"],
    colors: ["Pink", "Black", "Cream"],
    sizes: ["One Size"],
    description: "Elegant women's handbag with spacious compartments.",
    category: "women-bags"
  },
  {
    id: 12,
    name: "Silver Bracelet",
    price: 50.00,
    image: "../images/silver-bracelet.jpg",
    images: ["../images/silver-bracelet.jpg"],
    colors: ["Silver"],
    sizes: ["One Size"],
    description: "Stylish silver bracelet with a sleek modern design.",
    category: "women-jewellery"
  },
  {
    id: 13,
    name: "Classic Men's Suit",
    price: 299.99,
    image: "../images/Classic_Mens's_Suit_1.jpg",
    images: ["../images/Classic_Mens's_Suit_2.jpg", "../images/Classic_Mens's_Suit_3.jpg"],
    colors: ["Navy", "Grey", "Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "A timeless classic suit for men, perfect for formal occasions and business meetings.",
    category: "men-clothes"
  },
  {
    id: 14,
    name: "Women's Summer Dress",
    price: 45.00,
    image: "../images/Women's_Summer_Dress_1.jpg",
    images: ["../images/Women's_Summer_Dress_2.jpg", "../images/Women's_Summer_Dress_1.jpg"],
    colors: ["Yellow", "Floral", "White"],
    sizes: ["XS", "S", "M", "L"],
    description: "Light and airy summer dress, ideal for sunny days and casual outings.",
    category: "women-dresses"
  },
  {
    id: 15,
    name: "Sports Smartwatch",
    price: 180.00,
    image: "../images/Sports_Smartwatch_2.jpg",
    images: ["../images/Sports_Smartwatch_2.jpg", "../images/Sports_Smartwatch_2.jpg"],
    colors: ["Black", "Silver", "Rose Gold"],
    sizes: ["One Size"],
    description: "Advanced smartwatch with fitness tracking, heart rate monitor, and notifications.",
    category: "men-watches" // Can also be for women-watches
  },
  {
    id: 16,
    name: "Designer Leather Wallet",
    price: 60.00,
    image: "../images/Designer_Leather_Wallet_1.jpg",
    images: ["../images/Designer_Leather_Wallet_2.jpg", "../images/Designer_Leather_Wallet_1.jpg"],
    colors: ["Brown", "Black"],
    sizes: ["One Size"],
    description: "Premium leather wallet with multiple card slots and a coin pocket.",
    category: "men-belts" // Assuming belts category for men's accessories
  },
  {
    id: 17,
    name: "Pearl Earrings",
    price: 85.00,
    image: "../images/Pearl_Earrings_2.jpg",
    images: ["../images/Pearl_Earrings_1.jpg", "../images/Pearl_Earrings_3.jpg"],
    colors: ["White", "Pink"],
    sizes: ["One Size"],
    description: "Elegant pearl earrings, perfect for adding a touch of sophistication to any outfit.",
    category: "women-jewellery"
  },
  {
    id: 18,
    name: "Unisex Hiking Boots",
    price: 110.00,
    image: "../images/Unisex_Hiking_Boots_1.jpg",
    images: ["../images/Unisex_Hiking_Boots_2.jpg", "../images/Unisex_Hiking_Boots_1.jpg"],
    colors: ["Khaki", "Brown"],
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    description: "Durable and comfortable hiking boots for all terrains, suitable for both men and women.",
    category: "women-shoes" // Could also be men-shoes
  },
  {
    id: 19,
    name: "Slim Fit Jeans",
    price: 70.00,
    image: "../images/Slim_Fit_Jeans_2.jpg",
    images: ["../images/Slim_Fit_Jeans_1.jpg", "../images/Slim_Fit_Jeans_3.jpg"],
    colors: ["Blue", "Black", "Grey"],
    sizes: ["28", "30", "32", "34", "36", "38"],
    description: "Stylish slim-fit jeans, a versatile addition to any wardrobe.",
    category: "men-clothes"
  },
  {
    id: 20,
    name: "Knitted Cardigan",
    price: 50.00,
    image: "../images/Knitted_Cardigan_1.jpg",
    images: ["../images/Knitted_Cardigan_2.jpg", "../images/Knitted_Cardigan_3.jpg"],
    colors: ["Beige", "Navy", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
    description: "Soft and warm knitted cardigan, perfect for layering.",
    category: "women-dresses" // Or women-clothes
  },
  {
    id: 21,
    name: "Sport Sunglasses",
    price: 30.00,
    image: "../images/Sport_Sunglasses_1.jpg",
    images: ["../images/Sport_Sunglasses_2.jpg", "../images/Sport_Sunglasses_2.jpg"],
    colors: ["Black", "Blue Mirror"],
    sizes: ["One Size"],
    description: "Lightweight and protective sports sunglasses, ideal for outdoor activities.",
    category: "women-jewellery" // General accessory, placing under jewellery for women's general accessories
  },
  {
    id: 22,
    name: "Classic Oxford Shoes",
    price: 95.00,
    image: "../images/Classic_Oxford_Shoes_2.jpg",
    images: ["../images/Classic_Oxford_Shoes_1.jpg", "../images/Classic_Oxford_Shoes_2.jpg"],
    colors: ["Brown", "Black"],
    sizes: ["40", "41", "42", "43", "44"],
    description: "Elegant leather oxford shoes, a staple for any formal or business attire.",
    category: "men-shoes"
  },
  {
    id: 23,
    name: "Crossbody Bag",
    price: 70.00,
    image: "../images/Crossbody_Bag_1.jpg",
    images: ["../images/Crossbody_Bag_2.jpg", "../images/Crossbody_Bag_3.jpg"],
    colors: ["Black", "Cream", "Olive"],
    sizes: ["One Size"],
    description: "Compact and stylish crossbody bag, perfect for essentials on the go.",
    category: "women-bags"
  },
  {
    id: 24,
    name: "Men's Polo Shirt",
    price: 40.00,
    image: "../images/Men's_Polo_Shirt_1.jpg",
    images: ["../images/Men's_Polo_Shirt.jpg_1.jpg", "../images/Men's_Polo_Shirt_1.jpg"],
    colors: ["Blue", "White", "Green"],
    sizes: ["S", "M", "L", "XL"],
    description: "Comfortable and versatile polo shirt for men, suitable for casual and semi-formal wear.",
    category: "men-clothes"
  }
];
